# Generated by Django 5.2.8 on 2026-02-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the institution'),
        ),
        migrations.AddField(
            model_name='institution',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='institutions/'),
        ),
    ]
