# Generated by Django 5.2.8 on 2026-02-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_institution_description_institution_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(help_text='Contact number for verification.', max_length=20)),
                ('category', models.CharField(choices=[('PALLIATIVE', 'Palliative Care (സാന്ത്വനം)'), ('MARRIAGE', 'Marriage Aid (വിവാഹസഹായ നിധി)'), ('MEDICAL', 'Medical Aid (ചികിത്സാ സഹായം)'), ('EDUCATION', 'Educational Scholarship (സ്കോളർഷിപ്പ്)'), ('WIDOW', 'Widow Support (അതിജീവിതം)'), ('OTHER', 'Other / General')], max_length=20)),
                ('description', models.TextField(help_text='Describe your situation and requirement.')),
                ('document', models.FileField(blank=True, help_text='Upload supporting documents (medical reports, etc.)', null=True, upload_to='charity_docs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes by committee.')),
            ],
            options={
                'verbose_name': 'Charity Application',
                'verbose_name_plural': 'Charity Applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
