# Generated by Django 5.2.8 on 2026-02-09 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        ('core', '0003_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admission_applications_institution', to='core.institution'),
        ),
    ]
