# Generated by Django 5.2.8 on 2026-02-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('STUDENT', 'Student'), ('PARENT', 'Parent'), ('SPONSOR', 'Sponsor'), ('COMMITTEE', 'Committee Member'), ('APPLICANT', 'Applicant')], default='STAFF', max_length=20, verbose_name='role'),
        ),
    ]
