# Generated by Django 5.0 on 2026-02-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_staffprofile_department_staffprofile_joining_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Active WhatsApp number', max_length=20),
        ),
    ]
