# Generated by Django 5.0 on 2026-02-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_studentprofile_address_studentprofile_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='mobile_number',
            field=models.CharField(default='', help_text='Contact Number', max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='place',
            field=models.CharField(default='', help_text='City/Town/Village', max_length=100),
        ),
    ]
