# Generated by Django 5.2.8 on 2026-02-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_staffprofile_address_staffprofile_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='max_marks',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subject',
            name='pass_marks',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=5),
        ),
    ]
